/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareTeamRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.Room;
import Business.FinalAssignment;
import Business.FinalAssignmentCatalog;
import Business.Inventory.InventoryItemAssignment;
import Business.Inventory.InventoryItemAssignmentCatalog;
import Business.Organization.CareTeamOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrganizationManagerWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class ScheduleRoomsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CareTeamOrganization organization;
    private HospitalEnterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private int enterpriseId;
    private OrganizationManagerWorkRequest omwr;
    FinalAssignmentCatalog fac;
    //FinalAssignment fa;
    String date = null;
    String slot = null;

    public ScheduleRoomsJPanel(JPanel userProcessContainer, UserAccount account,
            CareTeamOrganization organization, HospitalEnterprise enterprise, EcoSystem system, int enterpriseId, OrganizationManagerWorkRequest omwr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.enterpriseId = enterpriseId;
        this.omwr = omwr;
        fac = EcoSystem.getFinalAssignmentCatalog();

        populateRoomCombo();
        populateHelperCombo();
    }

    public void populateRoomCombo() {
        roomCombo.removeAllItems();
        for (InventoryItemAssignment ia : omwr.getInventoryItemAssignmentCatalog().getInventoryItemAssignmentList()) {
            date = ia.getSchedule().getDate();
            slot = ia.getSchedule().getSlot();
            dateJTxt.setText(date);
            slotTxt.setText(slot);
            break;
        }
        for (Room r : enterprise.getRoomCatalog().getRoomCatalog()) {
            boolean flag = fac.verifyRoomAvailability(r, date, slot);
            if (flag == false) {
                roomCombo.addItem(r);
            }

        }

    }

    public void populateHelperCombo() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getName().equalsIgnoreCase(Organization.Type.Helper.getValue())) {
                for (Employee e : org.getEmployeeDirectory().getEmployeeList()) {
                    helperCombo.addItem(e);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roomCombo = new javax.swing.JComboBox();
        scheduleBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        helperCombo = new javax.swing.JComboBox();
        dateJTxt = new javax.swing.JTextField();
        slotTxt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Schedule Rooms Work Area");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(" Slot");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Select Room");

        roomCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roomCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboActionPerformed(evt);
            }
        });

        scheduleBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        scheduleBtn.setText("Schedule");
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Select Helper");

        helperCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helperComboActionPerformed(evt);
            }
        });

        dateJTxt.setEditable(false);

        slotTxt.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateJTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(slotTxt)
                            .addComponent(roomCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(helperCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(scheduleBtn)))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(slotTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(helperCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(scheduleBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        // TODO add your handling code here:
        Room room = (Room) roomCombo.getSelectedItem();
        FinalAssignment fa = fac.addAssignment();
        Employee helper = (Employee) helperCombo.getSelectedItem();

        fa.setHelper(helper);
        fa.getRoomAssignment().setRoom(room);
        fa.getRoomAssignment().getRoomschedule().setDate(date);
        fa.getRoomAssignment().getRoomschedule().setSlot(slot);
        fa.setHospitalEnterprise(enterprise);
        InventoryItemAssignmentCatalog ita = omwr.getInventoryItemAssignmentCatalog();
        for (InventoryItemAssignment itemAssignment : ita.getInventoryItemAssignmentList()) {
            itemAssignment.getInventoryItem().incrementUsageCounter();
        }

        fa.setInventoryItemAssignmentcatalog(ita);
        fa.setDoctor(omwr.getDoctorUserAccount().getEmployee());
        fa.setPatient(omwr.getPatient());
        omwr.setStatus("Scheduling Completed");
        JOptionPane.showMessageDialog(this, "Congratulations!!Scheduling completed successfully");
        System.out.println("Scheduling completed successfully");
    }//GEN-LAST:event_scheduleBtnActionPerformed


    private void roomComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomComboActionPerformed

    private void helperComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helperComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helperComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateJTxt;
    private javax.swing.JComboBox helperCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox roomCombo;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JTextField slotTxt;
    // End of variables declaration//GEN-END:variables
}
