/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.EcoSystem;
import Business.Enterprise.SupplierEnterprise;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaintainenceTestWorkRequest;
import Business.WorkQueue.OrganizationManagerWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class MaintainenceRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private EcoSystem system;
    private SupplierEnterprise supplierenterprise;
    private SupplierOrganization supplierOrganization;

    public MaintainenceRequestJPanel(JPanel userProcessContainer, UserAccount useraccount, SupplierEnterprise supplierenterprise, EcoSystem system,
            SupplierOrganization supplierOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.system = system;
        this.supplierenterprise = supplierenterprise;
        this.supplierOrganization = supplierOrganization;
        populateMaintainenceTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        maintainenceTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        completeMaintainenceBtn = new javax.swing.JButton();

        maintainenceTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RequestDate", "Sender", "Receiver", "Equipment", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(maintainenceTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Equipment Maintainence Work Area ");

        completeMaintainenceBtn.setText("Complete Maintainence");
        completeMaintainenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeMaintainenceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(completeMaintainenceBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(completeMaintainenceBtn)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void completeMaintainenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeMaintainenceBtnActionPerformed
        int selectedRow = maintainenceTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a row");
            return;
        }
        MaintainenceTestWorkRequest mtwr = (MaintainenceTestWorkRequest) maintainenceTbl.getValueAt(selectedRow, 0);
        mtwr.setStatus("Maintainence Completed");
        
        mtwr.setReceiver(useraccount);
        mtwr.getInventoryItem().setUsageCounter(0);
        mtwr.getInventoryItem().setMaintainenceStatus("MaintainenceCompleted");
        System.out.println("The maintainence completed successfully");
        populateMaintainenceTable();

    }//GEN-LAST:event_completeMaintainenceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeMaintainenceBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintainenceTbl;
    // End of variables declaration//GEN-END:variables

    private void populateMaintainenceTable() {
        DefaultTableModel model = (DefaultTableModel) maintainenceTbl.getModel();
        model.setRowCount(0);
        for (WorkRequest request : supplierOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof MaintainenceTestWorkRequest) {
                MaintainenceTestWorkRequest omTest = (MaintainenceTestWorkRequest) request;
                Object[] row = new Object[5];
                row[0] = omTest;
                row[1] = omTest.getSender();
                row[2] = omTest.getReceiver() == null ? null : omTest.getReceiver().getEmployee().getName();
                row[3] = omTest.getInventoryItem().getOrderitem().getProductItem().getProductName();
                row[4] = omTest.getStatus();
                model.addRow(row);
            }

        }

    }
}
