/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.WarehouseManagerRole;

import Business.EcoSystem;
import Business.Enterprise.RequiredDevice;
import Business.Enterprise.WarehouseEnterprise;
import Business.Inventory.InventoryItem;
import Business.Inventory.MaintainenceHistoryCatalog;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaintainenceTestWorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ViewMaintainenceHistoryWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Organization organization;
    private WarehouseEnterprise warehouseenterprise;
    private EcoSystem system;
    private MaintainenceHistoryCatalog mhc;
    private MaintainenceTestWorkRequest mtwr;
   
    public ViewMaintainenceHistoryWorkArea(JPanel userProcessContainer,WarehouseEnterprise warehouseenterprise,
            EcoSystem system,UserAccount useraccount,MaintainenceTestWorkRequest mtwr) {
        initComponents();  
         this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.warehouseenterprise = warehouseenterprise;
        this.system = system;
        this.mtwr=mtwr;
        populateMaintainenceTable();
     //   mhc = EcoSystem.getMaintainenceHistoryCatalog();
        
    }
    
    
   public void  populateMaintainenceTable (){
        DefaultTableModel model = (DefaultTableModel) maintainenceHistoryTbl.getModel();
        model.setRowCount(0);
        for (InventoryItem inventoryItem: mtwr.getMhc().getMaintainenceList()) {            
            Object[] row = new Object[2];
            row[0] = inventoryItem.getOrderitem().getProductItem().getProductName();
            row[1] = inventoryItem.getLogDate();
            model.addRow(row);
        }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintainenceHistoryTbl = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("View Maintainence History");

        maintainenceHistoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ItemName", "MaintainenceDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(maintainenceHistoryTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintainenceHistoryTbl;
    // End of variables declaration//GEN-END:variables
}
