/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.IntegerVerifier;
import Business.Organization.CareTeamOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.StringVerifier;
import Business.Surgery;
import Business.Surgery.SurgeryType;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReceptionistTestWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class CreateNewRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HospitalEnterprise hospitalEnterprise;
    private EcoSystem system;
    private UserAccount useraccount;

    public CreateNewRequestJPanel(JPanel userProcessContainer,
            HospitalEnterprise hospitalEnterprise, UserAccount useraccount, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.hospitalEnterprise = hospitalEnterprise;
        this.system = system;
        populateSurgery();
        populatePreferredDate();
        InputVerifier integerverifier = new IntegerVerifier();
        InputVerifier stringverifier = new StringVerifier();
        nameJTxt.setInputVerifier(stringverifier);
        ageJTxt1.setInputVerifier(integerverifier);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sexJLabel = new javax.swing.JLabel();
        nameJTxt = new javax.swing.JTextField();
        ageJTxt1 = new javax.swing.JTextField();
        sexCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        bckJBtn = new javax.swing.JButton();
        submitJBtn = new javax.swing.JButton();
        dateJLabel = new javax.swing.JLabel();
        preferredDateCombo = new javax.swing.JComboBox();
        surgeryJLabel = new javax.swing.JLabel();
        surgeryCombo = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Patient Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Patient Age");

        sexJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sexJLabel.setText("Gender");

        sexCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Create New Request");

        bckJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bckJBtn.setText("<<Back");
        bckJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckJBtnActionPerformed(evt);
            }
        });

        submitJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitJBtn.setText("Submit");
        submitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBtnActionPerformed(evt);
            }
        });

        dateJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateJLabel.setText("Prefferd Date");

        preferredDateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        preferredDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferredDateComboActionPerformed(evt);
            }
        });

        surgeryJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        surgeryJLabel.setText("Surgery Type");

        surgeryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bckJBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateJLabel)
                                            .addComponent(surgeryJLabel))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sexCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(preferredDateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(surgeryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(sexJLabel)
                                            .addComponent(jLabel2))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ageJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(submitJBtn)))))))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ageJTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateJLabel)
                    .addComponent(preferredDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surgeryJLabel)
                    .addComponent(surgeryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bckJBtn)
                    .addComponent(submitJBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBtnActionPerformed
        // TODO add your handling code here:
        if (nameJTxt.getText().length() > 0 && ageJTxt1.getText().length() > 0) {

            Patient patient = hospitalEnterprise.getPatientcatalog().addPatient();
            patient.setAge(Integer.parseInt(ageJTxt1.getText()));
            patient.setPatientName(nameJTxt.getText());
            patient.setSex(String.valueOf(sexCombo.getSelectedItem()));
            ReceptionistTestWorkRequest rct = useraccount.getWorkQueue().addRequst();
            rct.setPatient(patient);
            rct.setSender(useraccount);
            rct.setPreferredDate(String.valueOf(preferredDateCombo.getSelectedItem()));
            SurgeryType surgerytype = (SurgeryType) surgeryCombo.getSelectedItem();
            rct.setSurgery(String.valueOf(surgerytype));
            rct.setStatus("Sent");
            rct.setEnterpriseId(hospitalEnterprise.getEnterpriseid());

            Organization org = null;
            for (Organization organization : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CareTeamOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(rct);
                // useraccount.getWorkQueue().getWorkRequestList().add(rct);
            }
            System.out.println("New request created for Careteam");
             nameJTxt.setText("");
             ageJTxt1.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "The textbox cannot be blank ");
        }


    }//GEN-LAST:event_submitJBtnActionPerformed

    private void preferredDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferredDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferredDateComboActionPerformed

    private void bckJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bckJBtnActionPerformed

    private void populateSurgery() {
        surgeryCombo.removeAllItems();
        for (Surgery.SurgeryType type : Surgery.SurgeryType.values()) {
            surgeryCombo.addItem(type);
        }

    }

    private void populatePreferredDate() {

        preferredDateCombo.removeAllItems();
        String preferredDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        for (int i = 0; i < 60; i++) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Calendar calender = Calendar.getInstance();
            calender.add(Calendar.DATE, i); // it gives  the number of days we need to add
            preferredDate = dateFormat.format(calender.getTime());
            preferredDateCombo.addItem(preferredDate);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTxt1;
    private javax.swing.JButton bckJBtn;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameJTxt;
    private javax.swing.JComboBox preferredDateCombo;
    private javax.swing.JComboBox sexCombo;
    private javax.swing.JLabel sexJLabel;
    private javax.swing.JButton submitJBtn;
    private javax.swing.JComboBox surgeryCombo;
    private javax.swing.JLabel surgeryJLabel;
    // End of variables declaration//GEN-END:variables
}
